# Generated by Django 3.2.9 on 2021-12-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpcall',
            name='parameters',
        ),
        migrations.AddField(
            model_name='parameter',
            name='call',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.httpcall'),
            preserve_default=False,
        ),
    ]
